## In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow(or TPU)
* Exercises to try for yourself!!

## Introduction to tensors

In [6]:
# import TensorFlow
import tensorflow as tf

In [7]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
# Checks the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [9]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [10]:
vector.ndim

1

In [11]:
# create a matrix(has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [12]:
matrix.ndim 
    

2

In [13]:
# Create another matrix
another_matrix = tf.constant([10.,7.],[3.,2.],[8.,9.], dtype=tf.float16)
another_matrix

TypeError: Cannot convert the argument `type_value`: [3.0, 2.0] to a TensorFlow DType.