## Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [3]:
!pip install numpy

In [4]:
import numpy as np

## create array using numpy
## create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5))

array([[1, 2, 3, 4, 5]])

In [6]:
arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [7]:
arr3.reshape(1,10)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]])

In [8]:
arr3.reshape(10,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [9]:
arr3.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,10,11)

array([0])

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
## Attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape) # Output: (2,3)
print("Number of dimensions:",arr.ndim) # Output: 2
print("Size (number of elements):",arr.size) # Output: 6
print("Data type:",arr.dtype) # Output: int64 (may vary based on platform)
print("Item size (in bytes):",arr.itemsize) # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [17]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element Wise addition
print("Addition:", arr1+arr2)

## Element wise substraction
print("Substraction:",arr1-arr2)

## Element wise multiplication
print("Multiplication:",arr1*arr2)

## Element wise division
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [24]:
## Universal Function
arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## cosine
print(np.cos(arr))

## tan
print(np.tan(arr))

## log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [27]:
## Array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
print(arr[0])

[1 2 3 4]


In [31]:
print(arr[0][0])

1


In [35]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [36]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [41]:
print(arr[1:])
print(arr[0:2,2:])

[[ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]


In [43]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [44]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [45]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [46]:
## Statistical concepts -- Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
Normalized_data = (data - mean)/std_dev
print("Normalized data:",Normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [47]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean:",mean)

# Median
median = np.median(data)
print("Median:",median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)

# Variance
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [49]:
## Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [52]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])