## Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 24.3 MB/s  0:00:00m0:00:010:01


In [10]:
import numpy as np

## create array using numpy
## create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5))

array([[1, 2, 3, 4, 5]])

In [15]:
arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [16]:
arr3.reshape(1,10)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]])

In [19]:
arr3.reshape(10,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [20]:
arr3.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])