## Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 24.3 MB/s  0:00:00m0:00:010:01


In [10]:
import numpy as np

## create array using numpy
## create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5))

array([[1, 2, 3, 4, 5]])

In [15]:
arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [16]:
arr3.reshape(1,10)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]])

In [19]:
arr3.reshape(10,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [20]:
arr3.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.arange(0,10,11)

array([0])

In [25]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.ones(3)

array([1., 1., 1.])

In [30]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape) # Output: (2,3)
print("Number of dimensions:",arr.ndim) # Output: 2
print("Size (number of elements):",arr.size) # Output: 6
print("Data type:",arr.dtype) # Output: int64 (may vary based on platform)
print("Item size (in bytes):",arr.itemsize) # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8
